### ISSUE TITLE
Enable fargate spot for Maestro

### ISSUE THREAD

**Issue by HaseoBoss** [veezor/maestro_infra#7]
Execute the following command to enable fargate spot

aws --region us-east-1 ecs put-cluster-capacity-providers --cluster "cluster-name" --capacity-providers FARGATE FARGATE_SPOT --default-capacity-provider-strategy capacityProvider=FARGATE

**Comment by fagianijunior** [comment]
Feature added in PR https://github.com/veezor/maestro_infra/pull/8
